export const sharedPopupProps = [
  "round",
  "zIndex",
  "closeable",
  "overlay",
  "overlayClass",
  "overlayStyle",
  "destroyOnClose",
  "forceRender",
  "lockScroll",
  "duration",
  "transition",
  "closeOnClickOverlay",
  "closeOnPopstate",
  "onClickOverlay",
  "safeAreaInsetBottom",
  "onOpen",
  "onClose",
  "onOpened",
  "onClosed",
  "beforeClose",
] as const;
