name: 🐛 Bug Report
description: Something is wrong with React Vant Next.
title: "🐛 [Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing!

        Do you need some help?
        ======================
        The issue tracker is meant for feature requests and bug reports only. This isn't the best place for
        support or usage questions. Questions here don't have as much visibility as they do elsewhere. Before
        you ask a question, here are some resources to get help first:

        - Check our GitHub repository: https://github.com/silentlee/react-vant-next
        - Ask in GitHub Discussions: https://github.com/silentlee/react-vant-next/discussions

        ### Test Case Starter:
        - Create a minimal reproduction case using React and @react-vant-next/ui

        ### Code Example:

        - Check our repository for example code

  - type: checkboxes
    id: packages
    attributes:
      label: Which React Vant Next packages are impacted?
      options:
        - label: "`@react-vant-next/ui` (React Vant Next core)"
        - label: "`@react-vant-next/icons` (React Vant Next Icon)"
  - type: input
    attributes:
      label: What version of React Vant Next are you using?
    validations:
      required: true
  - type: input
    attributes:
      label: Reproduce live demo(codesandebox or stackblitz)?
  - type: markdown
    attributes:
      value: Please provide a link to a minimal reproduction of the issue
  - type: textarea
    attributes:
      label: Descripition
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: markdown
    attributes:
      value: Thanks for completing our form!
